services:
  - type: web
    name: wallet-masters
    runtime: node
    buildCommand: npm install
    startCommand: node bot.js
    healthCheckPath: /health
    plan: free
    region: oregon
    envVars:
      - key: BOT_TOKEN
        value: 8633930645:AAFWs_DngutMwsrGUjYi7M0f9ymgbJF47Xc
      - key: ADMIN_CHAT_ID
        value: "5995434559"
      - key: BOT_USERNAME
        value: walletmastersbot
      - key: FEE_ADDRESS
        value: TPwUS8v77TtcsYZUHUTvVx2TGqE37QnagZ
      - key: MINI_APP_URL
        value: https://wallet-masters.onrender.com
      - key: PORT
        value: "3000"
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.cuuekllbcrxvlxlydyta:ZiEPZYqgmCZaIgf2@aws-0-us-west-1.pooler.supabase.com:6543/postgres
      - key: SUPABASE_URL
        value: https://cuuekllbcrxvlxlydyta.supabase.co

